CREATE EXTENSION IF NOT EXISTS CITEXT;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id        SERIAL PRIMARY KEY NOT NULL,
  nickname  CITEXT UNIQUE NOT NULL,
  name      CITEXT NOT NULL,
  phone     CITEXT UNIQUE NOT NULL,
  status    CITEXT NOT NULL
);

DROP TABLE IF EXISTS rooms CASCADE;
CREATE TABLE rooms (
  id    SERIAL PRIMARY KEY NOT NULL,
  name  CITEXT NOT NULL,
  about CITEXT NOT NULL
);

DROP TABLE IF EXISTS members CASCADE;
CREATE TABLE members (
  user_id   INTEGER REFERENCES users(id) NOT NULL,
  room_id   INTEGER REFERENCES rooms(id) NOT NULL,
  toilet_paper_count INTEGER,
  pay_ability BOOLEAN DEFAULT TRUE,
  valuable BOOLEAN DEFAULT TRUE
);
